name: to_do_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
    
  hive: ^2.0.4
  hive_flutter: ^1.1.0  
  flutter_slidable: ^4.0.0 
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: asset/fonts/JosefinSans-Light.ttf
        - asset: asset/fonts/JosefinSans-Medium.ttf
        - asset: asset/fonts/JosefinSans-Regular.ttf
        - asset: asset/fonts/JosefinSans-SemiBold.ttf
        - asset: asset/fonts/JosefinSans-Bold.ttf
